version: "3.9" # Asegúrate de usar una versión válida

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: product_orders_app
        restart: unless-stopped
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: product-orders
            DB_USERNAME: root
            DB_PASSWORD: root
        volumes:
            - .:/var/www/html
        ports:
            - "8081:80"
        depends_on:
            - db
        networks:
            - app-network
        user: "www-data:www-data"

    webserver:
        image: nginx:latest
        container_name: nginx
        restart: always
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8082:80"
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: product-orders
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8083:80"
        depends_on:
            - db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
